### ISSUE TITLE
Compile libjingle_peerconnection_java.jar

### ISSUE THREAD

**Issue by HuuNguyen312** [RWebRTC/WebRTC-Android-Learn#4]
How to use "libjingle_peerconnection_java-src" replace for libjingle_peerconnection_java.jar

**Comment by RWebRTC** [comment]
@ngochuu90 Compile it in webrtc-android. 

Reference

http://renyuzhuo.cn/#/issues/2

 https://webrtc.org/native-code/android/

https://chromium.googlesource.com/external/webrtc
