### ISSUE TITLE
JNI

### ISSUE THREAD

**Issue by flyminiboy** [RWebRTC/WebRTC-Android-Learn#6]
JOW(jlong, PeerConnectionFactory_nativeCreatePeerConnectionFactory)(
    JNIEnv* jni, jclass, jobject joptions)
我想问一下 这个JOW 在那个地方定义的呢？ 还有他的第一个参数是指第二个参数代表的函数的返回值的类型吗？

**Comment by RWebRTC** [comment]
@fly518420 JOW 在哪里定义的我不是很清楚, 第一个参数是第二个参数代表的函数的返回值的类型。

**Comment by flyminiboy** [comment]
我自己在Java文件里面新增native方法是不是只需要在 peerconnection.cc 里面进行类似的实现就行，还需要的其他操作吗？

**Comment by RWebRTC** [comment]
@fly518420 正常jni，没有其他操作
