### ISSUE TITLE
依赖库

### ISSUE THREAD

**Issue by flyminiboy** [RWebRTC/WebRTC-Android-Learn#8]
我使用你直接编译好的jingle_peerconnection_so动态库，提示需要其他的依赖库，可以不使用那些依赖库吗？因为我信令那一部分没有使用官网的那一套

**Comment by RWebRTC** [comment]
@fly518420 应该还是需要的，依赖库没有的话本身也不好运行或运行出错。建议还是加上依赖库

**Comment by flyminiboy** [comment]
Java文件那一一层，我直接把源码导入到工程里面，是不是就不需要
autobanh.jar
base_java.jar
libjingle_peer_connection.jar
这三个了

**Comment by RWebRTC** [comment]
@fly518420 导文件也挺费劲的，可以试试

**Comment by flyminiboy** [comment]
autobanh.jar 这个是不是进行websocket 信令交互的啊？
Java那一层没有问题，但是总是在arm64-v8a 里面 jingle_peerconnection_so 这个奔溃

**Comment by RWebRTC** [comment]
@fly518420 这个我不很清楚，good luck

**Comment by ggggxiaolong** [comment]
@fly518420 autobanh.jar 提供的是webscoket的支持，如果是和web界面通信的话，是通过websocket交换信令的
